### ISSUE TITLE
Consider bootstrap 4 implications

### ISSUE THREAD

**Issue by zkamvar** [carpentries/varnish#1]
There is a lot of discussion buzzing about the R community to switching over to bootstrap 4.

Examples: 

https://github.com/r-lib/pkgdown/issues/1409
https://github.com/rstudio/rmarkdown/issues/1260
https://github.com/rstudio/rmarkdown/issues/1260#issuecomment-548004630

It may be worthwhile just to go with bootstrap4 from the get-go and see if we can tool around that.

**Comment by zkamvar** [comment]
I knew this would fail, but the first test with swapping out the script sources for bootstrap 4 and jQuery gives this monstrosity:

![image of mis-rendered web page with 3 errors, 1 warning, and 85 debug flags](https://user-images.githubusercontent.com/3639446/97503494-5d576580-1932-11eb-9636-874fa389741e.png)

**Comment by fmichonneau** [comment]
bootstrap 5 is coming out soon, when using it with our own version of the template, we need to look into whether we should skip version 4 altogether.

**Comment by zkamvar** [comment]
I think we may want to start with 4 and migrate to 5 once the RMarkdown verse is also there. At the moment, they are still on 4, but are considering 5: https://github.com/rstudio/bslib/issues/82

 One of the things I've been eyeing is using {bslib} and a custom RMarkdown template to control the theming. In theory, this should allow people to more easily customize the template for their use.
