### ISSUE TITLE
Software Carpentry logo looks a bit wonky

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/varnish#107]
The alignment/spacing/kerning (not sure if I'm using that last word correctly) of the text in the Software Carpentry logo seems a bit uneven:

![software-logo-original](https://github.com/carpentries/varnish/assets/9694524/f2a75681-9754-4f36-bbb4-71fb5de077ed)

If the Maintainers agree, I would like to open a PR that will replace that logo SVG with one I have adjusted slightly to better match the way the text appears in the logo elsewhere:

![software-logo](https://github.com/carpentries/varnish/assets/9694524/078329d4-d801-4761-a707-0f88a495d486)

**Comment by ErinBecker** [comment]
thank you @tobyhodges. This change would be welcomed.
