### ISSUE TITLE
callout text in allcaps

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/varnish#128]
We received an issue on instructor training [about calltouts being in all cap case](https://github.com/carpentries/instructor-training/issues/1646) 

I was able to trace through inspection that the `callout-title` css class has `text-transform:uppercase` set and that that class is applied to the whole callout `<div> ` in addition to the callout title `<h3>` but I am not familiar enough with this pacakage to put in a PR. 

It seems the solution should be to remove that class from the callout `<div>` and apply it to only the `<h3>

**Comment by tobyhodges** [comment]
This was fixed by @froggleston in https://github.com/carpentries/sandpaper/pull/574

**Comment by ErinBecker** [comment]
Thanks for the follow up @tobyhodges. Yes, this is closed with https://github.com/carpentries/sandpaper/pull/574
