### ISSUE TITLE
Markdown To Do List not Formatting Correctly

### ISSUE THREAD

**Issue by jq-11** [carpentries/varnish#156]
Hello!

I'm facing an error using markdown in a carpentries lesson. I am trying to create a to-do list, but instead of the correct markdown output, an incorrect version is produced.

For example,
the following markdown code 
```
- [ ] To-do point
```
appears like this

<img width="117" alt="Screenshot 2024-11-04 at 5 02 37 PM" src="https://github.com/user-attachments/assets/4edd7e58-e9b5-4310-a252-e7281ff60320">

According to the markdown documentation, this markdown code:

```
- [ ] incomplete task
- [x] completed task
```

should look like this:
<img width="153" alt="Screenshot 2024-11-04 at 5 06 53 PM" src="https://github.com/user-attachments/assets/36fb244e-7987-444f-abc0-79d5d4027474">

I noticed this is also a bug on the current sandpaper docs website: https://carpentries.github.io/sandpaper-docs/index.html#:~:text=Automatic%20updates,Compatible%20with%20RStudio

Is there any way to solve this?

**Comment by froggleston** [comment]
Hi @jq-11 - thanks for raising the issue! Yes, this is down to the CSS for checklists being suboptimal. I've worked through an example locally and managed to get them looking better: 
![image](https://github.com/user-attachments/assets/24a83ae0-9740-4eb9-afac-e7d7a7283148)

I'll include this in the next release, which should be available early next week.

**Comment by jq-11** [comment]
@froggleston
Thank you so much! It looks great now!

**Comment by froggleston** [comment]
Awesome!
