### ISSUE TITLE
Replace Lab logo files

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/varnish#59]
I'd like to replace the `lab-logo.svg` (a) and `lab-logo-sm.svg` (b) files in varnish (`source/images/`) with updated versions:

a:
![carpentrieslab](https://user-images.githubusercontent.com/9694524/188157764-dc3cd057-cdd3-4798-9072-7a1e60e4de90.svg)

b:
![carpentrieslab-simple](https://user-images.githubusercontent.com/9694524/188157757-9a064bd0-f73e-4052-97c8-bf585ba67689.svg)

**Comment by zkamvar** [comment]
Not necessarily a blocker: but I'm wondering if we should update the lab logo to use our brand colors instead.

**Comment by zkamvar** [comment]
Also: do you want to give a go at replacing these logos? The live in https://github.com/carpentries/varnish/tree/main/source/images

**Comment by tobyhodges** [comment]
This new version uses more of our brand identity than the previous version, but does still stray a little outside that range too.
