### ISSUE TITLE
callout square is slightly off position on chrome

### ISSUE THREAD

**Issue by zkamvar** [carpentries/varnish#60]
The callout square on desktop is slightly off-kilter on the Chrome browser. 

![cropped screenshot of a blue callout square whose right edge slightly overlaps the box it is supposed to sit next to](https://user-images.githubusercontent.com/3639446/188209773-0e2995f0-479f-4cd4-9766-03330b35c50e.png)

I believe the culprit is here:

https://github.com/carpentries/varnish/blob/85363d9e15ee65c0ccff914d091c7369c252b2ff/source/stylesheets/callouts.scss#L185

If I shift it to `-44px`, then it works on Chrome, Firefox, and Opera browsers with the slight disappointment of causing the left hand side of the squares being 1px to the left of the main content.

**Comment by ErinBecker** [comment]
This no longer appears to be an issue. Tested in Firefox: 
<img width="631" alt="Screenshot 2024-07-09 at 10 45 42 AM" src="https://github.com/carpentries/varnish/assets/19176319/302f02fd-4e49-4868-8cc5-adfe4715977c">

And Chrome: 
<img width="678" alt="Screenshot 2024-07-09 at 10 45 34 AM" src="https://github.com/carpentries/varnish/assets/19176319/f9369219-dfc7-4f9c-96d0-c29bd5b7c71e">
