### ISSUE TITLE
Bullets in instructor notes formatting off

### ISSUE THREAD

**Issue by sstevens2** [carpentries/varnish#68]
<img width="753" alt="screen shot of instructor note with bullet points that are not aligned with the items" src="https://user-images.githubusercontent.com/5558419/205086600-dd898538-7dc6-432f-a1a1-00e130a85e33.png">

Noticed the bullet points are a bit off in the instructor training in-line instructor notes.

@zkamvar Investigated more in this gif and suggests the `list-style-position` css attribute needs to be updated
![gif showing the same screenshot with a devtools window open, toggling the list-style-position CSS property and having the list items align](https://user-images.githubusercontent.com/5558419/205086645-200c0306-099d-48e0-a713-2e9321fbe917.gif)

**Comment by zkamvar** [comment]
I just fixed it and it should update on https://carpentries.r-universe.dev/ui#package:varnish within the hour.

When it does, we can rebuild the site (or wait for it to rebuild on Monday) and it will be fixed.
