### ISSUE TITLE
Heading word wrap inconsistency

### ISSUE THREAD

**Issue by jd-foster** [carpentries/varnish#83]
I'm seeing the below wrapping effect (see "Questions"):
![image](https://github.com/carpentries/varnish/assets/38274066/c2cd829b-4a3b-4b3d-a7b2-3525e3f5bc21)

I'm using Firefox (v112+ on mac), where it's most prominent, but it occurs at a much smaller range of window widths in Chrome too.

https://github.com/carpentries/varnish/assets/38274066/afe47930-eac9-4fdf-b4c6-a67e43886905

**Comment by zkamvar** [comment]
Thank you for opening this and for providing the demonstrations. 

This is very related to https://github.com/carpentries/sandpaper/issues/299 (via https://github.com/carpentries/workbench/discussions/10#discussioncomment-2938302). I will see what I can do.

**Comment by Robadob** [comment]
Appears this issue has resurfaced #112
