### ISSUE TITLE
Lesson title div does not take into account size of searchbox

### ISSUE THREAD

**Issue by ocaisa** [carpentries/varnish#84]
While starting to contribute to a new lesson, I noticed that the wrapping of the lesson title does not take into account the size of the  searchbox (at least in my current setup):
![Screenshot (71)](https://github.com/carpentries/varnish/assets/3840437/3a132a79-5cff-4da1-8bab-ddf52068a57f)

**Comment by zkamvar** [comment]
Thank you for opening this! It's definitely a bug with the CSS. I'll see what I can do.
